Converted tabs to spaces as per guidelines

diff --git a/files/usr/bin/application-bootstrap b/files/usr/bin/application-bootstrap
--- a/files/usr/bin/application-bootstrap
+++ b/files/usr/bin/application-bootstrap
@@ -10,8 +10,8 @@ set -e
 
 cd /var/www
 if [ -e "passenger_wsgi.py" ] || [ -e "manage.py" ]; then 
-	echo "ERROR: Django application already present in /var/www"
-	exit 1
+    echo "ERROR: Django application already present in /var/www"
+    exit 1
 fi
 
 # Move the supervisor files to accommodate the enable / disable / remove scripts
diff --git a/files/usr/bin/application-migrator b/files/usr/bin/application-migrator
--- a/files/usr/bin/application-migrator
+++ b/files/usr/bin/application-migrator
@@ -11,8 +11,8 @@ set -e
 
 cd /var/www
 if [ ! -e "manage.py" ]; then 
-	echo "ERROR: Django application not present in /var/www"
-	exit 1
+    echo "ERROR: Django application not present in /var/www"
+    exit 1
 fi
 
 source application-python-environment
