Updated application scripts to correctly take advantage of enable/disable system

diff --git a/files/usr/bin/application-bootstrap b/files/usr/bin/application-bootstrap
--- a/files/usr/bin/application-bootstrap
+++ b/files/usr/bin/application-bootstrap
@@ -5,6 +5,9 @@ echo "Application Bootstrap"
 # This is intended to be used as part of the build process
 #
 
+# Stop on error
+set -e
+
 cd /var/www
 if [ -e "passenger_wsgi.py" ] || [ -e "manage.py" ]; then 
 	echo "ERROR: Django application already present in /var/www"
@@ -28,7 +31,7 @@ source application-python-environment
 
 # Install some Django basics to ensure this image functions standalone in a fashion that makes sense.
 pip install --no-cache-dir --upgrade pip
-pip install --no-cache-dir --upgrade django-celery django
+pip install --no-cache-dir --upgrade django-celery==3.1.17 django==1.9.4
 django-admin startproject -v 3 app .
 cp -v app/wsgi.py passenger_wsgi.py
 echo "" > app/settings.py.new
diff --git a/files/usr/bin/application-component-remove b/files/usr/bin/application-component-remove
--- a/files/usr/bin/application-component-remove
+++ b/files/usr/bin/application-component-remove
@@ -1,17 +1,20 @@
 #!/usr/bin/env bash
 
+# Stop on error
+set -e
+
 COMPONENT=$1
 
-if [ -z "$COMPONENT" ]; then
+if [[ -z "$COMPONENT" ]]; then
     echo "ERROR: No component name passed to application-component-remove"
     exit 1
 fi
 
-if [ "$COMPONENT" = "all" ]; then
+if [[ "$COMPONENT" = "all" ]]; then
     echo "Refusing to remove all components"
     exit 2
 
-elif [ "$COMPONENT" = "web" ]; then
+elif [[ "$COMPONENT" = "web" ]]; then
     echo "Removing application web component"
     rm -f /etc/supervisor/conf.d.template/logs.conf
     rm -f /etc/supervisor/conf.d.template/nginx.conf
diff --git a/files/usr/bin/application-migrator b/files/usr/bin/application-migrator
--- a/files/usr/bin/application-migrator
+++ b/files/usr/bin/application-migrator
@@ -6,6 +6,9 @@ echo "Application Migrate"
 # $ docker run ubuntu-16-django-application application-migrate
 #
 
+# Stop on error
+set -e
+
 cd /var/www
 if [ ! -e "manage.py" ]; then 
 	echo "ERROR: Django application not present in /var/www"
@@ -16,17 +19,20 @@ source application-python-environment
 echo ""
 echo ""
 
+# Get the initial status so that it can be logged
 python /var/www/manage.py showmigrations
 echo ""
 echo ""
 
+# Do the migration
 python /var/www/manage.py migrate
 echo ""
 echo ""
 
+# Report the new status
 python /var/www/manage.py showmigrations
 echo ""
 echo ""
 
-rm /etc/supervisor/conf.d/*.conf
+# Wait to be told that we need to start again
 exec /init/supervisord
diff --git a/files/usr/bin/application-scheduler b/files/usr/bin/application-scheduler
--- a/files/usr/bin/application-scheduler
+++ b/files/usr/bin/application-scheduler
@@ -6,6 +6,9 @@ echo "Application Scheduler"
 # $ docker run ubuntu-16-django-application application-scheduler
 #
 
+# Stop on error
+set -e
+
 cd /var/www
 if [ ! -e "manage.py" ]; then 
     echo "ERROR: Django application not present in /var/www"
@@ -13,12 +16,8 @@ if [ ! -e "manage.py" ]; then
 fi
 
 if [ -z "$1" ]; then
-    # No command line arguments
-
-    rm /etc/supervisor/conf.d/nginx.conf
-    rm /etc/supervisor/conf.d/logs.conf
-    rm /etc/supervisor/conf.d/worker.conf
-
+    # No command line arguments ... assume being called as docker run argument
+    application-component-enable scheduler
     exec /init/supervisord
 else
     # Execute our scheduler
diff --git a/files/usr/bin/application-web b/files/usr/bin/application-web
--- a/files/usr/bin/application-web
+++ b/files/usr/bin/application-web
@@ -6,6 +6,9 @@ echo "Application Web Interface"
 # $ docker run ubuntu-16-django-application application-web
 #
 
+# Stop on error
+set -e
+
 cd /var/www
 if [ ! -e "manage.py" ]; then 
     echo "ERROR: Django application not present in /var/www"
@@ -14,7 +17,5 @@ fi
 
 # No command line arguments
 
-rm /etc/supervisor/conf.d/worker.conf
-rm /etc/supervisor/conf.d/scheduler.conf
-
+application-component-enable web
 exec /init/supervisord
